# Defenitions of training objects
# object type is one of CUBE, SPHERE, CYLIINDER, MESH
objects:
  #- object:
  #    type: CUBE
  #    tag_id: 331
  #    tag_offset: {x: 0.0, y: 0.0, z: 0.025}
  #    scale: {x: 0.05, y: 0.1, z: 0.05}
  #    tags: [11, 12, 13]
  - object:
      type: CUBE
      tag_id: 352
      tag_offset: {x: 0.0, y: 0.0, z: 0.056}
      scale: {x: 0.162, y: 0.23, z: 0.112}
      tags: [11, 12, 13]
  - object:
      type: SPHERE
      tag_id: 202
      tag_offset: {x: 0.0, y: 0.0, z: 0.0}
      scale: {x: 0.1, y: 0.1, z: 0.1}
      tags: [21, 22, 23]
  - object:
      type: CYLINDER
      tag_id: 203
      tag_offset: {x: 0.0, y: 0.0, z: 0.0}
      scale: {x: 0.1, y: 0.1, z: 0.1}
      tags: [31, 32, 33]
#  - object:
#      type: MESH
#      mesh: '<path_to_mesh>'
#      tags: [41, 42, 43]
#      scale: {x: 0.1, y: 0.1, z: 0.1}
